apiVersion: batch/v1
kind: Job
metadata:
  name: usage-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: df-checker
          image: busybox:1.36
          command: [ "sh", "-c" ]
          args:
            - |
              # skip header row
              df -h /mnt/data* | tail -n +2;
          volumeMounts: []
      volumes: []